version: '3.9'
services:
  mongo:
    image: mongo:4.1.8-xenial
    container_name: mongo
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASS
      - MONGO_INITDB_DATABASE=$DB
    networks:
      - app-network
  bot:
    depends_on:
      - mongo
    container_name: bot
    restart: unless-stopped
    image: "${DOCKER_USER}/${BOT_NAME}"
    build: bot
    env_file:
      - .env
    volumes:
      - ./bot:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: /home/node/app/node_modules/.bin/nodemon app.js
  nginx:
    build: nginx
    container_name: nginx
    image: "${DOCKER_USER}/loadbalancer"
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  db:
  node_modules:

networks:
  app-network:
    driver: bridge