version: '3.9'
services:
  mongo:
    image: mongo:4
    container_name: mongo
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASS
      - MONGO_INITDB_DATABASE=$DB
    networks:
      - app-network
  bot:
    depends_on:
      - mongo
    container_name: $BOT_NAME
    restart: unless-stopped
    image: "${DOCKER_USER}/${BOT_NAME}"
    build: bot
    env_file:
      - .env
    labels:
      - traefik.http.routers.blog.rule=Host(`$BOT_NAME.your_domain`)
      - traefik.http.routers.blog.tls=true
      - traefik.http.routers.blog.tls.certresolver=lets-encrypt
      - traefik.port=$BOT_PORT
    volumes:
      - ./bot:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
      - web
    command: /home/node/app/node_modules/.bin/nodemon app.js

volumes:
  db:
  node_modules:

networks:
  web:
    external: true
  app-network:
    driver: bridge
    external: false